# Database layer for Credit Intelligence Agent
# Persists generated credit intelligence records to SQLite (dev) / PostgreSQL (prod)
# Prevents duplicate processing and enables audit logging

from sqlalchemy import (
    create_engine,
    Column,
    String,
    Float,
    DateTime,
    Text,
    JSON,
    Boolean,
    Integer,
    event,
)
from sqlalchemy.orm import DeclarativeBase, sessionmaker, Session
from sqlalchemy.exc import IntegrityError
from datetime import datetime, timezone
from typing import Optional
import os
import logging

logger = logging.getLogger(__name__)

# ── Database URL ───────────────────────────────────────────────────────────────
# Override via env var for PostgreSQL in production:
# CREDIT_DB_URL=postgresql+psycopg2://user:pass@host:5432/creditdb
DATABASE_URL = os.getenv("CREDIT_DB_URL", "sqlite:///./credit_intelligence.db")

# ── Engine Setup ───────────────────────────────────────────────────────────────
# check_same_thread=False is SQLite-only; safe because SQLAlchemy manages
# connection pooling. Remove this kwarg when switching to PostgreSQL.
_connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

engine = create_engine(
    DATABASE_URL,
    connect_args=_connect_args,
    echo=os.getenv("DB_ECHO", "false").lower() == "true",  # set DB_ECHO=true to log SQL
    pool_pre_ping=True,   # validates connections before use (important for long-lived apps)
)

SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


# ── ORM Base ───────────────────────────────────────────────────────────────────
class Base(DeclarativeBase):
    pass


# ── Models ─────────────────────────────────────────────────────────────────────

class CreditIntelligenceRecord(Base):
    """
    Stores one credit intelligence result per (borrower_id, loan_id) pair.
    The composite unique key prevents duplicate processing.
    """
    __tablename__ = "credit_intelligence"

    # Primary key: deterministic compound ID so upserts are safe
    # Format: BRW-XXXXXXXX_LN-XXXXXXXX
    record_id           = Column(String(64),  primary_key=True)

    # Foreign references (no FK constraint — agents are decoupled)
    borrower_id         = Column(String(32),  nullable=False, index=True)
    loan_id             = Column(String(32),  nullable=False, index=True)

    # Risk outputs
    risk_score          = Column(Float,       nullable=False)          # 0-100
    default_probability = Column(Float,       nullable=False)          # 0.0-1.0
    recommendation      = Column(String(16),  nullable=False)          # APPROVE|REVIEW|DECLINE

    # Structured risk factors stored as JSON array of strings
    risk_factors        = Column(JSON,        nullable=False, default=list)

    # Free-text fields generated by Sarvam LLM
    market_insights     = Column(Text,        nullable=False, default="")
    narrative           = Column(Text,        nullable=True)           # optional extended memo

    # Sarvam model metadata — useful for auditing which model produced the record
    model_used          = Column(String(64),  nullable=True)           # e.g. "sarvam-m"
    language_code       = Column(String(8),   nullable=True)           # e.g. "en-IN"

    # Processing flags
    is_duplicate        = Column(Boolean,     default=False)           # True if re-processed
    processing_attempts = Column(Integer,     default=1)               # retry counter

    # Timestamps
    generated_at        = Column(DateTime,    nullable=False,
                                  default=lambda: datetime.now(timezone.utc))
    updated_at          = Column(DateTime,    nullable=True,
                                  onupdate=lambda: datetime.now(timezone.utc))

    def __repr__(self) -> str:
        return (
            f"<CreditIntelligenceRecord "
            f"record_id={self.record_id!r} "
            f"risk_score={self.risk_score} "
            f"recommendation={self.recommendation!r}>"
        )


class CreditIntelligenceEvent(Base):
    """
    Append-only audit log for every processing event (success, retry, error).
    Never update or delete rows here — this is your audit trail.
    """
    __tablename__ = "credit_intelligence_events"

    event_id    = Column(Integer,    primary_key=True, autoincrement=True)
    record_id   = Column(String(64), nullable=False, index=True)   # matches CreditIntelligenceRecord
    borrower_id = Column(String(32), nullable=False)
    loan_id     = Column(String(32), nullable=False)

    # Event classification
    event_type  = Column(String(32), nullable=False)
    # Values: "CREATED" | "DUPLICATE_SKIPPED" | "RETRY" | "ERROR" | "QUERIED"

    message     = Column(Text,       nullable=True)   # human-readable detail or error string
    created_at  = Column(DateTime,   nullable=False,
                          default=lambda: datetime.now(timezone.utc))

    def __repr__(self) -> str:
        return (
            f"<CreditIntelligenceEvent "
            f"event_id={self.event_id} "
            f"event_type={self.event_type!r} "
            f"record_id={self.record_id!r}>"
        )


# ── DB Lifecycle ───────────────────────────────────────────────────────────────

def init_db() -> None:
    """
    Create all tables if they don't exist.
    Call once at agent startup inside FastAPI @app.on_event("startup").
    Safe to call multiple times — SQLAlchemy uses CREATE TABLE IF NOT EXISTS.
    """
    Base.metadata.create_all(bind=engine)
    logger.info("Credit Intelligence DB initialised at: %s", DATABASE_URL)


def get_db():
    """
    FastAPI dependency — yields a scoped session and closes it after the request.

    Usage in route:
        @app.post("/intelligence")
        async def create(db: Session = Depends(get_db)):
            ...
    """
    db = SessionLocal()
    try:
        yield db
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


# ── CRUD Helpers ───────────────────────────────────────────────────────────────

def build_record_id(borrower_id: str, loan_id: str) -> str:
    """Deterministic primary key — same inputs always produce the same key."""
    return f"{borrower_id}_{loan_id}"


def get_intelligence_record(
    db: Session,
    borrower_id: str,
    loan_id: str,
) -> Optional[CreditIntelligenceRecord]:
    """
    Fetch an existing intelligence record by borrower + loan.
    Returns None if not found — use this to check for duplicates before processing.
    """
    record_id = build_record_id(borrower_id, loan_id)
    return (
        db.query(CreditIntelligenceRecord)
        .filter(CreditIntelligenceRecord.record_id == record_id)
        .first()
    )


def save_intelligence_record(
    db: Session,
    borrower_id: str,
    loan_id: str,
    risk_score: float,
    default_probability: float,
    recommendation: str,
    risk_factors: list[str],
    market_insights: str,
    model_used: Optional[str] = None,
    language_code: Optional[str] = "en-IN",
    narrative: Optional[str] = None,
) -> tuple[CreditIntelligenceRecord, bool]:
    """
    Insert a new record or increment the attempt counter on a duplicate.

    Returns:
        (record, was_duplicate)
        was_duplicate=True means this borrower+loan pair was already processed.

    Duplicate handling strategy:
        - First call  → INSERT new record,          log CREATED event
        - Repeat call → UPDATE attempt counter,     log DUPLICATE_SKIPPED event
          (does NOT overwrite risk_score — preserves original decision)
    """
    record_id = build_record_id(borrower_id, loan_id)

    # ── Check for existing record ──────────────────────────────────────────────
    existing = (
        db.query(CreditIntelligenceRecord)
        .filter(CreditIntelligenceRecord.record_id == record_id)
        .first()
    )

    if existing:
        # Duplicate: increment counter and flag it, but preserve original scores
        existing.processing_attempts += 1
        existing.is_duplicate = True
        existing.updated_at = datetime.now(timezone.utc)
        db.commit()
        db.refresh(existing)

        _log_event(
            db,
            record_id=record_id,
            borrower_id=borrower_id,
            loan_id=loan_id,
            event_type="DUPLICATE_SKIPPED",
            message=(
                f"Duplicate processing attempt #{existing.processing_attempts} "
                f"for borrower={borrower_id}, loan={loan_id}. "
                f"Original scores preserved."
            ),
        )
        logger.warning(
            "Duplicate credit intelligence request for record %s (attempt #%d)",
            record_id,
            existing.processing_attempts,
        )
        return existing, True

    # ── Fresh insert ───────────────────────────────────────────────────────────
    record = CreditIntelligenceRecord(
        record_id=record_id,
        borrower_id=borrower_id,
        loan_id=loan_id,
        risk_score=risk_score,
        default_probability=default_probability,
        recommendation=recommendation,
        risk_factors=risk_factors,
        market_insights=market_insights,
        model_used=model_used,
        language_code=language_code,
        narrative=narrative,
        generated_at=datetime.now(timezone.utc),
    )

    try:
        db.add(record)
        db.commit()
        db.refresh(record)
    except IntegrityError:
        # Race condition: another request inserted the same record_id concurrently
        db.rollback()
        logger.error(
            "IntegrityError on record_id=%s — possible race condition. "
            "Consider adding a distributed lock for high-concurrency deployments.",
            record_id,
        )
        raise

    _log_event(
        db,
        record_id=record_id,
        borrower_id=borrower_id,
        loan_id=loan_id,
        event_type="CREATED",
        message=f"risk_score={risk_score}, recommendation={recommendation}",
    )
    logger.info(
        "Saved credit intelligence: record_id=%s risk=%.1f rec=%s",
        record_id, risk_score, recommendation,
    )
    return record, False


def log_error_event(
    db: Session,
    borrower_id: str,
    loan_id: str,
    error_message: str,
) -> None:
    """
    Record a failed processing attempt in the audit log.
    Call this in your exception handlers so failures are traceable.
    """
    record_id = build_record_id(borrower_id, loan_id)
    _log_event(
        db,
        record_id=record_id,
        borrower_id=borrower_id,
        loan_id=loan_id,
        event_type="ERROR",
        message=error_message,
    )


def get_events_for_loan(
    db: Session,
    loan_id: str,
) -> list[CreditIntelligenceEvent]:
    """Fetch all audit events for a specific loan — useful for debugging."""
    return (
        db.query(CreditIntelligenceEvent)
        .filter(CreditIntelligenceEvent.loan_id == loan_id)
        .order_by(CreditIntelligenceEvent.created_at.asc())
        .all()
    )


# ── Internal Helper ────────────────────────────────────────────────────────────

def _log_event(
    db: Session,
    record_id: str,
    borrower_id: str,
    loan_id: str,
    event_type: str,
    message: Optional[str] = None,
) -> None:
    """
    Internal helper — appends one row to the audit log.
    Uses a separate flush so the event is always written even if the
    caller rolls back their own transaction.
    """
    event = CreditIntelligenceEvent(
        record_id=record_id,
        borrower_id=borrower_id,
        loan_id=loan_id,
        event_type=event_type,
        message=message,
        created_at=datetime.now(timezone.utc),
    )
    db.add(event)
    db.commit()   # commit to make sure event is persisted